keploy/docs

.github/workflows/main.yml

Updates actions-yarn to `3.0.0` to fix python 2 not found problem. The latest version has been migrated to python 3.

ci: update yarn action to fix python version bug

---

src/css/custom.css

- Added firefox operating guide bullets and text alignment fix
Fixes # (49)
- [*] Bug fix (non-breaking change which fixes an issue).
- Manual
...

Closes #49 - firefox operating guide bullets and text alignment fix

---

sidebars.js

The link to next button for `Java SDK Integartion` in keploy server installation page need to be updated for Java.
Fixes https://github.com/keploy/keploy/issues/321

fix(sidebar): Java SDK installation link

---

src/css/custom.css

It is a simple bug causing alignment issues fixed by custom code targeting the element.
Fixes #325 raised in keploy main repository.
https://github.com/keploy/keploy/issues/325Fixes # (issue)
Local Test
...

Fixing home icon alignment-added padding on top and margin on bottom

---

docs/go/quickstart/gorillamux-redis.md

The image of Keploy console is removed, as the same content is displayed using shell. 
Fixes [#557](https://github.com/keploy/keploy/issues/557)

[docs] removed the extra image of Keploy console

---

src/theme/DocItem/index.js

If we go to:
- [https://docs.keploy.io/docs/keploy-explained/introduction](https://docs.keploy.io/docs/keploy-explained/introduction)
- [https://docs.keploy.io/docs/devtools/sdk-contrib-guide](https://docs.keploy.io/docs/devtools/sdk-contrib-guide)
- [https://docs.keploy.io/docs/gsoc/contribution-guide](https://docs.keploy.io/docs/gsoc/contribution-guide)
- [https://docs.keploy.io/docs/go/installation](https://docs.keploy.io/docs/go/installation)
...and almost every section of the website, we can see a redundant footer like in the screenshot floating at the bottom unnecessarily.
I have fixed the unnecessary import of this footer in the issue [#568](https://github.com/keploy/keploy/issues/568)
Fixes [#568](https://github.com/keploy/keploy/issues/568)
Fixes …

bug: redundant footer

---

.github/workflows/build_and_check.yml
docusaurus.config.js

[dropdownItemsAfter](https://docusaurus.io/docs/api/themes/configuration#navbar-docs-version-dropdown-dropdownItemsAfter) is used to add additional dropdown items. So earlier there were 2 version items in the dropdown plus an additional item added through `dropdownItemsAfter` with no [label](https://docusaurus.io/docs/api/themes/configuration#navbar-docs-version-label).
Fixes # (keploy/keploy#834)
...

fix: bug (keploy#834)

---

src/components/QuickStart.js
versioned_docs/version-2.0.0/concepts/what-are-keploy-features.md
versioned_docs/version-2.0.0/concepts/what-is-keploy.md
versioned_docs/version-2.0.0/keploy-explained/introduction.md

docs: change intro page keploy and it's features

---

versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/quickstart/samples-mux.md

Removed the --rm flag 
Fixes # ([946](https://github.com/keploy/keploy/issues/946))
...

removed --rm flag for record and test cmd

---

versioned_docs/version-1.0.0/concepts/index.md
versioned_docs/version-1.0.0/concepts/what-are-keploy-features.md
versioned_docs/version-1.0.0/go/quickstart/quickstart.md
versioned_docs/version-2.0.0/server/index.md
yarn.lock

Fixes faulty URLs 
Fixes keploy/keploy#973
No tests as of now.

Fixes faulty URLs

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md

chore: adding examples of flags

---

versioned_docs/version-2.0.0/quickstart/samples-bunjs.md

Resolves issue #1235 where the documentation for the sample bun.js contained a typo in the command for capturing test cases. The current command incorrectly references Keploy instead of the correct alias keploy.
Updated the documentation in bun.js to reflect the correct command for capturing test cases.
Replaced Keploy with the appropriate alias keploy as previously set.
**Issue number** : [#1134](https://github.com/keploy/keploy/issues/1134)

 Fix: Typo in command for capturing test cases in sample bun.js documentation

---

versioned_docs/version-2.0.0/running-keploy/configuration-file.md

Added usage of filters in Keploy-config.yaml in docs

Added the filter usage in docs

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md
versioned_docs/version-2.0.0/server/sdk-installation/go-sdk.md
versioned_docs/version-2.0.0/server/sdk-installation/java-sdk.md

Removed table of content
Fixes [#1269](https://github.com/keploy/keploy/issues/1269)
...

removed table of content

---

versioned_docs/version-1.0.0/java/quickstart/spring-sql.md
versioned_docs/version-2.0.0/quickstart/samples-java.md
versioned_docs/version-2.0.0/running-keploy/rename-testcases.md
versioned_docs/version-2.0.0/server/sdk-installation/go-sdk.md

Fixed the following issues
Fixes keploy/keploy#1274, Fixes keploy/keploy#1275
I checked the documentation generated by `yarn start` locally.
...

Fix `cd` destination and language of code blocks

---

src/components/GitTogether.js

This pull request adds a redirect link to the Gittogether Banner Image. When users click on the banner image, they will now be redirected to the designated URL.
- Added HTML anchor tag around the banner image.
- Specified the URL to redirect users to when clicking the banner.
- Tested the redirect functionality by clicking on the banner image in various browsers.
- Verified that users are correctly redirected to the specified URL.

feat: Added redirect link to Gittogether Banner Image

---

versioned_docs/version-2.0.0/server/sdk-installation/python-sdk.md

`import sys` is not required as well as how to install pytest wasn't mentioned anywhere in the guide, therefore have added `pip install keploy pytest`

feat: remove sys from import

---

.prettierrc.json

As discussed in Prettier's official blog https://prettier.io/blog/2021/09/09/2.4.0, I have removed the `jsxBracketSameLine` and added `bracketSameLine`.
Fixes https://github.com/keploy/keploy/issues/2092
1. Run `yarn prettier --write <path-to-file/filename>.md`
2. Doesn't generate any warning and performs check successfully.

Update `jsxBracketSameLine` to `bracketSameLine`

---

versioned_docs/version-2.0.0/running-keploy/configuration-file.md

This PR adds an example for handling deeply nested JSON fields in the Keploy configuration file. The added example illustrates how to specify paths for nested fields such as tokens in the global noise configuration.
Changes Made
Added an example JSON response demonstrating deeply nested fields.
Provided YAML configuration showing how to specify paths for nested fields in the global noise section.
Included detailed comments to help users understand the configuration.
Fixes https://github.com/keploy/keploy/issues/1892
Documentation Enhancement  
...

[docs]: added example for handling nested JSON fields

---

versioned_docs/version-2.0.0/keploy-explained/dev-guide.md

In the docs, it was mentioned that Keploy has 3 modes, but it has only 2 as of now, `record` and `test`.
Fixes https://github.com/keploy/keploy/issues/2139

fix: typo for no of modes

---

versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md

It includes the clear and concise steps to run django-postgres on native support

fix: update django-sql steps

---

versioned_docs/version-2.0.0/running-keploy/docker-tls.md

Docker TLS document has the wrong asset download URL.

Fixed Docker tls assets download command

---

versioned_docs/version-2.0.0/concepts/reference/glossary/mocks.md

Updated "Data Mocks using AI" page
Link to the page : https://keploy.io/docs/concepts/reference/glossary/mocks/

Updated Data Mocks using AI page

---

versioned_docs/version-2.0.0/concepts/reference/glossary/functional-testing.md

add image ref to main blog

---

src/components/Community.js
src/css/custom.css
tailwind.config.js

This PR addresses clipboard functionality issues in Safari. Additional styling adjustments were necessary due to conflicts arising from the solution.
* Disabled Tailwind preflight to resolve Safari clipboard issues
* Adjusted primary colors to maintain compatibility with Docusaurus' default color scheme  
* Updated font size and line height for better consistency
* Added viewBox attributes to YouTube and GitHub icons to prevent cropping
* Removed Roboto Bold from Tailwind config to address h3 and highlighted text font fallback issues (not related to this fix)
1. Run `npm run build` and `npm run serve` to verify changes
2. Please include screenshots of command outputs
3. Add screenshots/GIFs demonstrating the changes if possible

Hotfix: Fix Safari clipboard copy issue by disabling Tailwind preflight

---

src/components/Community.js
src/css/custom.css
tailwind.config.js

This PR includes the following changes:
- Fixed Safari clipboard issue by disabling Tailwind preflight.
- Added Tailwind preflight styles manually in custom.css.
- Fixed icon scaling issues caused by disabling preflight.
- Reset border-radius for images in table cells and disabled Roboto Bold to prevent font fallback issues.
This PR fixes clipboard copy issue on safari and fixes few styling issues.
- Ran `npm run build` and `npm run serve` to verify the changes.
- Checked clipboard functionality in Safari.
- Verified proper rendering of images and icons.

Fix safari clipboard copy issue

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

This pull request includes a change to the `versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md` file to update the instructions for downloading required JARs and the Keploy version. 
The most important changes include:
* Updated the step title to include downloading the Keploy version.
* Added a command to install the latest Keploy binary using a one-click script.
* Changed the JAR file name from `KeployAgent.jar` to `io.keploy.agent-2.0.1.jar` in both the download link and the `wget` command.

docs: update the karaf links

---

versioned_docs/version-2.0.0/quickstart/java-spring-boot-xml.md
versioned_docs/version-2.0.0/running-keploy/configuration-file.md

This pull request adds a new quickstart guide for creating a sample REST API with Spring Boot and XML. The guide includes instructions for setting up the environment, running the application, and integrating with Keploy for automated test case generation.
Documentation updates:
* [`versioned_docs/version-2.0.0/quickstart/java-spring-boot-xml.md`](diffhunk://#diff-f86f1bb651143cf0f92598d152278b7b8aa6648a1da6cddacd7db0f905806cf5R1-R153): Added a comprehensive guide for creating a REST API with Spring Boot and XML, including setup instructions, API endpoint examples, and integration with Keploy for test case generation.
Please run npm run build and npm run serve to check if the changes are working as expected. Please include screenshots of the …

docs: add support for xml

---

versioned_docs/version-2.0.0/keploy-explained/mac-linux.md

Update the installation steps for limactl in macOS
This PR Resolves [#2703](https://github.com/keploy/keploy/issues/2703)

fix(docs): steps for limactl installation

---

versioned_docs/version-3.0.0/running-keploy/cli-commands.md

This PR Resolves https://github.com/keploy/keploy/issues/2817

feat: add docs for metadata in config file

---

static/_redirects

I have fixed the issue with redirecting the old page to the new page, which will help improve the SEO score
Sample:

fix: duplicate redirect content issue

---

versioned_docs/version-3.0.0/running-keploy/generate-api-tests-using-ai.md

chore: update agent links

---

README.md
versioned_docs/version-3.0.0/running-keploy/generate-api-tests-using-ai.md
versioned_docs/version-3.0.0/running-keploy/review-and-improve-ai-generated-tests.md

**What changed:**
- Updated the documentation version reference in README.md from `version-2.0.0` to `version-3.0.0`
- Fixed the Vale linting command examples to point to the correct documentation version directory
**Why this change was needed:**
This fix ensures that the README instructions are accurate and point to the current documentation version. Users following the linting documentation instructions will now reference the correct versioned directory structure.
**Files changed:**
- `README.md` - Updated Vale command examples from `versioned_docs/version-2.0.0/` to `versioned_docs/version-3.0.0/`
**Type of change:**
**Testing:**
- Verified that the updated paths in the README match the actual documentation directory structure
- Commands in the README now reference the correct version …

fix: correct the docs version in the README

---

versioned_docs/version-3.0.0/running-keploy/cli-commands.md

This PR Resolves https://github.com/keploy/keploy/issues/2919

Documentation for report command in keploy oss

---

src/css/custom.css

Added space in the website between the search and them toggler
This PR Resolves https://github.com/keploy/keploy/issues/2943 #2943
- [*] Bug fix (non-breaking change which fixes an issue).
- [*] My code follows the style guidelines of this project.
- [*] I have performed a self-review of my own code.

added space between search and theme toggler

---

src/css/custom.css

Fixed the back-to-top button visibility issue by updating its styling in `custom.css`. The button was previously white and barely visible against light backgrounds, making it difficult for users to find and use. 
Updated the `.theme-back-to-top-button` CSS class to use Keploy's orange theme color (#FF914D) for the background with white icon/text for proper contrast. Added hover effects for better user experience.
This PR Resolves #3004
**Testing Steps:**
1. Navigate to any docs page
2. Scroll down until the back-to-top button appears
3. Verify the button is now orange (#FF914D) with white …

feat(docs): Update scroll-to-top icon color for visibility

---

src/pages/concepts/reference/glossary.js

This PR adds a "scroll-to-top" button to the Glossary page.
Previously, the Glossary page lacked this navigation feature, which is already present on other long-form content pages. This created an inconsistent user experience, requiring users to scroll manually to the top of a potentially long page.
This change utilizes the existing BackToTop component to ensure functional and visual consistency with the rest of the documentation site, improving overall usability.
This PR Resolves [#3086](https://github.com/keploy/keploy/issues/3086)
***Build Results***

Feature: Added "Back To Top Button" in Glossary Page
