.github/workflows/main.yml

This adds a Github Actions pipeline that automatically deploys the latest to the s3 bucket hosting the documentation website. It also invalidates the CloudFront cache to reflect the new changes.

ci: add github actions to deploy website

---

.github/ISSUE_TEMPLATE/config.yml
.github/config.yml
.github/pull_request_template.md
README.md

This PR Contains
Added Config Action for new users PR merge and al things
Update PR template
Added some info in readme

added info, config, pr template

---

.github/workflows/codeql.yml

This PR Contains
Added Codeql action for language matrix

added codeql action

---

.github/workflows/write-good.yml

This PR Contains
Added Prosebot GHA
This Github Action help in spelling checking
This is specially for docs, readme and markdown of any repo
This help in spelling , docs is correct or not

added prosebot GHA

---

docusaurus.config.js

Updates the Algolia search key
Fixes - search not working

chore: update the Algolia search key

---

docs/keploy-explained/why-keploy.md

The 'Why Keploy?' section consisted of only an image. 
I've added some content about Keploy.
Fixes #19 
Yes

Added content to 'Why Keploy' section

---

CONTRIBUTING.md
README.md
docs/devtools/sdk-contrib-guide.md
docs/devtools/server.md
docs/devtools/web-ui.md
docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md
docs/java/installation.md
docs/java/integration-with-junit.md
docs/java/run-your-first-app-tutorial.md
docs/server/introduction.md
docs/server/server-installation.md
sidebars.js
src/components/Intro.js
src/components/KeployCloud.js
src/components/QuickStart.js
src/components/SDKs.js
src/components/index.js
src/pages/index.js
src/pages/leadership.js
src/theme/BlogLayout/index.js

Signed-off-by: Sarthak Shyngle <50234097+Sarthak160@users.noreply.github.com>
...

docs(java): add installation and integration guide for java-sdk

---

src/components/Resources.js

I have fixed the Keploy spelling error.
Fixes #26 
Keploy spelling error bug fix

fix: fixed Keploy spelling error

---

docs/java/installation.md
docs/java/integration-with-junit.md
docs/java/run-your-first-app-tutorial.md

Signed-off-by: Sarthak Shyngle <50234097+Sarthak160@users.noreply.github.com>
- Update version for java keploy SDK dependency 
- Make changes acc to new test file for java sdk
...

refactor(docs): update maven version and change in test-file

---

docs/concepts/general-glossary.md
docs/concepts/what-are-keploy-features.md

Created a markdown file called ```general-glossary``` in the docs repository under ```docs/concepts``` and listed the description of specific terms. 
Fixes #34 

Added glossary describing complex terms

---

docs/operation/browser-extension.md
sidebars.js

Added documentation for the [Keploy Browser Extension](https://github.com/keploy/browser-extension)
Fixes #47 

Added doc for Keploy Browser Extension

---

docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md

Updated broken links with correct links in following:
Fixes #46

Fix broken links

---

docs/server/server-installation.md

Signed-off-by: Ritesh Dabral <riteshdabral1@gmail.com>
Changed the numbering on installation page.
Since there was only one main heading, it was unnecessary to number it, however the sub heading were not numbered. Hence this change
#51 
Simply run the server and in your browser hit <YOUR_LOCALHOST>/docs/server/introduction endpoint to see the relevant changes
...

Change numbers on installation doc

---

docs/concepts/what-is-a-keploy-sdk.md

Signed-off-by: Dinesh <dinesh.skini@gmail.com>
...

append forward slash

---

src/css/custom.css

Signed-off-by: Li0 <manojrajput762000@gmail.com>
fixing bottom margin of logo
Fixes #75
...

Fix : alignment of keploy logo in nav bar

---

src/components/Intro.js
src/css/custom.css

Signed-off-by: Li0 <manojrajput762000@gmail.com>
fixing SDKs element style
Fixes #79 

Fix element style

---

docs/go/installation.md

Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>
Fixes #54 
...

Remove SDK Modes content from Go-SDK Integration Page

---

docs/java/installation.md
docs/java/integration-with-junit.md
docs/java/run-your-first-app-tutorial.md

Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>
indentation fix
Fixes #55 
...

Improvements in Java SDK Doc

---

docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md

Signed-off-by: Manoj Marmat <manojrajput762000@gmail.com>
Fixes #53

Reduce the content in Gin-Mongo Smaple Doc 

---

docs/go/supported-frameworks.md

This PR is for these issues: https://github.com/keploy/go-sdk/issues/122 and https://github.com/keploy/go-sdk/issues/131
Added example for elastic-search integration with keploy.
...

docs(readme): add example for elastic-search and redis integration with keploy

---

CONTRIBUTING.md
README.md
docs/hacktoberfest/code-contribution.md
docs/hacktoberfest/contribution-guide.md
docs/hacktoberfest/non-code.md
docusaurus.config.js
sidebars.js
src/components/Hacktoberfest.js
src/components/Resources.js
src/components/index.js
src/pages/index.js

HacktoberFest : Docs Frontpage

---

docs/concepts/what-is-keploy.md
docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md
docs/go/quickstart/users-profile-sample-application.md
docs/server/server-installation.md
docusaurus.config.js
src/components/QuickStart.js

Signed-off-by: Neha Gupta <gneha21@yahoo.in>
...

feat: update new methods of installing keploy

---

docs/concepts/what-is-keploy.md
docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md
docs/go/quickstart/users-profile-sample-application.md
docs/server/server-installation.md
docusaurus.config.js
src/components/QuickStart.js

fix: Quickstart links

---

README.md
docs/go/index.md
docs/go/installation.md
docs/go/quickstart/gin-mongo-quickstart.md
docs/go/quickstart/run-your-first-app-tutorial.md
docs/go/quickstart/users-profile-sample-application.md
docs/go/supported-frameworks.md
docs/java/installation.md
docs/java/run-your-first-app-tutorial.md
docs/server/server-installation.md
docs/typescript/installation.md

changed port number (8080 , 8081) to 6789
Fixes # 92
documentation change
`Signed-off-by: ritik jain <ritikjain025@gmail.com>`

changed port number (8080 , 8081) to 6789

---

docusaurus.config.js
sidebars.js
src/pages/index.js

Signed-off-by: sonichigo <kurosakiichigo.songoku@gmail.com>
...

Hacktoberfest Section Removed

---

.github/workflows/main.yml

Signed-off-by: slayerjain <shubhamkjain@outlook.com>

ci: update gha pipeline to node 18

---

docs/server/introduction.md
docs/server/server-installation.md
yarn.lock

Signed-off-by: sonichigo <kurosakiichigo.songoku@gmail.com>
Fixes #106 

Docs update: New Keploy working & Broken Link Fix

---

docs/go/quickstart/run-your-first-app-tutorial.md

The documentation included some features that are available only on the ui of the app, but the documentation is only for the terminal.
...

fixed some errors in the quickstart guide

---

src/css/custom.css

Changed the top bar color to an orange shade to match Keploy's theme.
Fixes #27 
...

changed top bar color

---

docs/go/quickstart/gin-mongo-quickstart.md

The documentation did not mention starting the mongodb server. So when users where running the app they were getting a 500 Server Error. Added the instructions to start the mongo server to fix that
Signed-off-by: Pranshu Srivastava <iampranshu24@gmail.com>
...

docs(gin-mongo-sample): fix docs of starting the mongodb server

---

docs/go/quickstart/run-your-first-app-tutorial.md

Worked on the issue #118 and corrected the error
Did the necessary changes
Fixes #118 

Corrected the error

---

src/components/SDKs.js

Updated redirection link and removed WIP
Fixes #91 

updated redirection link and removed WIP

---

docs/devtools/docs-contrib-guide.md
docs/devtools/introduction.md
sidebars.js

I have added the contributing guidelines for docs website to the contributing section

added docs contributing guidelines to website

---

src/components/Intro.js

Fixed a broken link to the Go SDK in the documentation.
Fixes https://github.com/keploy/keploy/issues/317
...

Fixed broken link to Go SDK in the docs

---

src/components/Intro.js

Assigned by: @SanskritiHarmukh 
- TypeScript SDK Redirection Link updated.
- Also changed the order of presentation by putting TypeScript above Python in the list.
Fixes [#316](https://github.com/keploy/keploy/issues/316) (issue)

fix : Typescript SDK's redirection link updated

---

src/components/Community.js

[Keploy Student's Blogs](https://keploy.hashnode.dev/) has a wide range of blogs that can help beginners understand API, Testing, Mocks and Keploy. Thus Hashnode link is included in the Community section too.
Fixes # [319](https://github.com/keploy/keploy/issues/319)
...

fixes issue #319

---

CONTRIBUTING.md
src/css/custom.css

Fixed Logo overlapping bug in smaller screen sizes and fixed a  typo in contributing.md .
.
[ #138 ] 
Yes, it has been tested and fixed.
Fixed -
...

Logo overlapping and typo in contributing.md fix

---

docs/go/quickstart/quickstart.md
docs/java/quickstart/quickstart.md
docs/java/quickstart/spring-sql.md

Adding a one liner description for sample applications in quickstart index.

adding description to quickstart sample apps

---

docs/server/server-installation.md

Fixes [#296](https://github.com/keploy/keploy/issues/296)
I hosted and tested the docs on my local machine and then made the changes. I have checked the changes work perfectly by testing on my machine.

Fix Keploy Server Installation Guide

---

docs/java/integration.md

Added the [Java SDK HLD](https://github.com/keploy/keploy/issues/344) to java docs.

added HLD to java docs

---

README.md

feat: Issue Creation Note added

---

docs/go/supported-frameworks.md

I have updated the Supported Routers section in the integration part of the docs
I have checked the md file in vs code md file viewer.
...
- [✓ ] My code follows the style guidelines of this project.
- [✓ ] I have performed a self-review of my own code.
- [✓ ] I have made corresponding changes to the documentation.
- [ ✓] I have added corresponding tests.
- [ ✓] Any dependent changes have been merged and published in downstream modules.

docs : update the instructions for frameworks

---

.github/CLA.md
.github/workflows/build_and_check.yml
.github/workflows/cla.yml
.github/workflows/lint.yml
docs/devtools/web-ui.md

I have added the github workflows for executing few github actions:
CLA.yml - It checks whether the contributor has signed the Contributor License Agreements
Greetings.yml - It welcomes the first time contributors
Lint.yml - It checks the linting on push and pull request on main branch and checks out the code from the repository. It checks the linting whether th commit message and PR is using "feat" for a new feature, "fix" for a bug fix, or "docs" for documentation changes.
Build_and_check.yml - Checking the pull request preview

fix(.github): adds github workflows for CLA Assistant,Building & Linting

---

Dockerfile
docker-compose.yml
package.json
yarn.lock

Added docker file and docker compose file. 
Fixes #532
testing on the local hosts and using docker cmd.

feat: adding docker file

---

.github/workflows/cla.yml

CLA GitHub action version updated

fix: cla issue

---

src/css/custom.css
src/theme/DocItem/index.js

Fixes  #[552](https://github.com/keploy/keploy/issues/552)
Locally on my system
Previous:- 
1. ![image](https://github.com/keploy/docs/assets/53110238/45996937-aabd-42e0-9981-24b0839b88bd)
2. ![image](https://github.com/keploy/docs/assets/53110238/1426d7e4-971f-49b4-af28-5a64019a56a8)
Current:-

fix: duplicate footer & footer margin 

---

docusaurus.config.js
package.json
src/css/custom.css
static/robots.txt
yarn.lock

Seo: add robots txt, migrate docusaurus to v2

---

docs/go/installation.md
docs/go/quickstart/quickstart.md
docs/go/record.md
docs/go/replay.md
docs/go/supported-frameworks.md
docs/java/installation.md
docs/java/quickstart/quickstart.md
docs/java/record.md
docs/java/replay.md

fix: metadata description duplication corrected

---

docusaurus.config.js
static/scripts/clarity.js

feat: clarity code

---

sidebars.js
versioned_sidebars/version-1.0.0-sidebars.json
versioned_sidebars/version-2.0.0-sidebars.json

There are some duplication between the value of key `id` in `link` attribute and the values inside `items` attribute. 
Because of this, the collapser and the actual item in the sidebar both gets active (see the attached screenshot) when such a duplication is present. Since docasaurus uses the sidebar to generate "next" and "previous" pagination link [^1], so in our case the collapser[^2] is treated as active and "next" element after the collapser would be the actual item[^3]. This was the root cause of this error. Deleting the `link` attribute for those collapser which doesn't have a independent page will solve this issue.
Additional Changes: typo fix
[^1]: https://docusaurus.io/docs/sidebar/multiple-sidebars#generating-pagination.
[^2]: Example: …

832 Fix same page linked to the next button of pagination navbar

---

src/css/custom.css

Fixes # (keploy/keploy#629)
...

fix: hamburger drawer too close on small screens

---

.github/workflows/build_and_check.yml

fix ci pipeline for PR build and check 

---

versioned_sidebars/version-2.0.0-sidebars.json

Fixes # (keploy/keploy#832)
...

fix: navigation issue

---

docusaurus.config.js

Fixes # (keploy/keploy#803)
...

added json-ld data and preconnect link

---

.github/workflows/prettify_code.yml

Fixes # (keploy/keploy#407)
...

ci: add prettify code ci workflow

---

versioned_docs/version-2.0.0/keploy-explained/faq.md
versioned_docs/version-2.0.0/keploy-explained/why-keploy.md

docs: change why keploy and FAQ page

---

versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/windows/installation.md

Changed arm to amd in linux and windows installation 
Fixes # (keploy/keploy#839)
...

fix: change arm to amd in linux and windows installation

---

src/theme/NavbarItem/DropdownNavbarItem.js

Fixes # (keploy/keploy#811)
...

811 navigation not working in docs website

---

docusaurus.config.js
versioned_docs/version-2.0.0/server/index.md
versioned_sidebars/version-2.0.0-sidebars.json

chore: change sidebars and navbar

---

docusaurus.config.js
static/scripts/chat.js

feat: add chat-live

---

versioned_docs/version-1.0.0/concepts/general-glossary.md
versioned_docs/version-1.0.0/concepts/reference/glossary/unit-test-automation.md
versioned_docs/version-1.0.0/concepts/what-are-keploy-features.md
versioned_docs/version-1.0.0/concepts/what-are-keploy-sdk-modes.md
versioned_docs/version-1.0.0/keploy-explained/faq.md
versioned_docs/version-1.0.0/operation/record.md
versioned_docs/version-1.0.0/operation/test.md
versioned_docs/version-1.0.0/typescript/generate-tests.md
versioned_docs/version-1.0.0/typescript/installation.md
versioned_docs/version-1.0.0/typescript/mock-library.md

Updated the title and description of conflicting docs of Keploy v1 and v2.

fix: docs title and description changed

---

versioned_docs/version-2.0.0/quickstart/samples-gin.md

Fixes # (keploy/keploy#875)
...

docs: update the test command

---

versioned_docs/version-2.0.0/server/linux/installation.md

Fixes # (keploy/keploy#898)
...

docs: add arm section in linux installation

---

CONTRIBUTING.md

Fixes # (keploy/keploy#924)
...

fix: broken link

---

versioned_docs/version-2.0.0/quickstart/samples-nodejs.md

I have corrected this by updating the documentation to refer to the correct line number, which is line 4 in db/connection.js.
Fixes [#968](https://github.com/keploy/keploy/issues/968)

(fix):Typo in Sample node.js Application setup

---

versioned_docs/version-2.0.0/quickstart/samples-nodejs.md

I have updated the documentation to guide users to the 'express-mongoose' folder instead, ensuring a smooth setup process for users.
Fixes [#965](https://github.com/keploy/keploy/issues/965)
I have tested the updated instructions by following the documentation and verifying that it correctly directs users to the 'express-mongoose' folder, preventing the previously encountered error.
...

(fix):Update Folder Path in Setup application

---

versioned_docs/version-2.0.0/quickstart/samples-django.md

Created the documentation for samples-django application

feat: added samples-django documentation

---

versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md
versioned_docs/version-2.0.0/server/windows/installation.md

Adding one click install for documentation
https://github.com/keploy/keploy/issues/1054
...

add:one click install

---

versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md
versioned_docs/version-2.0.0/server/windows/installation.md

Updating the docs for one click install 
...

refactor:one click install update

---

versioned_docs/version-2.0.0/quickstart/go-gin-redis.md

feat: adding gin-redis sample app documentation

---

versioned_docs/version-2.0.0/quickstart/samples-django.md

fix: updated the django-postgres docs

---

versioned_docs/version-2.0.0/quickstart/samples-django.md

fix: app executions commands fixed

---

versioned_docs/version-2.0.0/quickstart/fastapi-twilio.md
versioned_docs/version-2.0.0/quickstart/flask-mongo.md
versioned_sidebars/version-2.0.0-sidebars.json

feat: added docs of fastapi-twilio and flask-mongo sample application

---

src/pages/index.js
versioned_sidebars/version-2.0.0-sidebars.json

Commented and removed the code related to hacktoberfest.
...

chore: hacktoberfest banners removed

---

versioned_sidebars/version-2.0.0-sidebars.json

docs: sidebar updated

---

versioned_docs/version-1.0.0/concepts/general-glossary.md
versioned_docs/version-2.0.0/concepts/general-glossary.md

Added definition for Deduplication Algorithm in the glossary section of the docs.
Closes [#1125](https://github.com/keploy/keploy/issues/1125)

docs: added definition for Deduplication Algorithm

---

versioned_docs/version-2.0.0/quickstart/samples-bunjs.md

Fixed typo
Fixes [#1168)](https://github.com/keploy/keploy/issues/1168)
Fixed Typo
...

fix: fixed typo in samples-bunjs

---

versioned_docs/version-2.0.0/keploy-explained/dev-guide.md

Minor changes in Doc

---

versioned_docs/version-2.0.0/quickstart/samples-bunjs.md

This PR changes the documentation structure of the sample BunJS app to follow a more standard structure.
- Updated the documentation structure.
- Ensured consistency with the established documentation standards.
- Updated content to reflect changes in the document structure.
...

fix: fixed structure of samples-bunjs

---

versioned_docs/version-2.0.0/quickstart/samples-echo.md

This PR changes the documentation structure of the sample Echo + Postgres app to follow a more standard structure.
- Updated the documentation structure.
- Ensured consistency with the established documentation standards.
- Updated content to reflect changes in the document structure.
...

fix: fixed structure of samples-echo

---

versioned_docs/version-2.0.0/running-keploy/configuration-file.md

the code snippets in configuration-file page were outdated and needed an update.
Fixes # (keploy/keploy#1180)

fix: add new keploy-config

---

versioned_docs/version-2.0.0/dependencies/mongo.md

Added some missing contexts that will help users to setup Keploy with MongoDB, and also added some examples which will help the users in better understanding.
Fixes [#1079](https://github.com/keploy/keploy/issues/1079)

(docs): Updated the MongoDB support doc

---

versioned_docs/version-2.0.0/keploy-explained/dev-guide.md
versioned_docs/version-2.0.0/quickstart/go-gin-mongo.md
versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-twilio.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/quickstart/samples-bunjs.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md

Updated the alias in docs to work with the current keploy version.

chore:updated the alias

---

versioned_docs/version-2.0.0/quickstart/go-mux-sql.md

Removed duplicates
Fixes [#1250](https://github.com/keploy/keploy/issues/1250)
Bug fix
...

fix: removed duplicates from go-mux-sql.md

---

versioned_docs/version-2.0.0/quickstart/go-mux-sql.md

Fixes: [#1258](https://github.com/keploy/keploy/issues/1258)
...

Fixed typo of catalog

---

versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md

Fixes [1268](https://github.com/keploy/keploy/issues/1268)
...

Updated title in samples app 

---

versioned_docs/version-2.0.0/quickstart/go-gin-mongo.md
versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-twilio.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/server/macos/installation.md

Fixes https://github.com/keploy/keploy/issues/1311
...

refactor:alias of keploy for docker-desktop

---

versioned_docs/version-2.0.0/quickstart/go-gin-mongo.md
versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-twilio.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/quickstart/samples-bunjs.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md

refactor:macos colima doc update

---

versioned_docs/version-2.0.0/quickstart/samples-java.md

Updated as per the slack conversation here - https://keploy.slack.com/archives/C035URHSGDQ/p1705509244317829

docs: fix java spring boot and postgres tutorial

---

versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md

Added missing prerequisites for Flask and pip installation

---

versioned_docs/version-2.0.0/keploy-explained/dev-guide.md
versioned_docs/version-2.0.0/quickstart/go-gin-mongo.md
versioned_docs/version-2.0.0/quickstart/go-gin-redis.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-twilio.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/quickstart/samples-bunjs.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md
versioned_docs/version-2.0.0/server/windows/installation.md

chore: change volume in docker alias

---

versioned_docs/version-2.0.0/quickstart/python-django-sql.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md

docker build is missing in MacOS guide added

---

docs/hacktoberfest/code-contribution.md

 updated title tags

---

versioned_docs/version-2.0.0/quickstart/go-mux-mysql.md

refactor: add mysql tag go-mux-mysql.md

---

versioned_docs/version-2.0.0/keploy-explained/dev-guide.md
versioned_docs/version-2.0.0/server/sdk-installation/java-sdk.md

Updated docs regarding recent integration of serve command in test command using coverage flag
Fixes  [#1313](https://github.com/keploy/keploy/issues/1313)
...

upating docs for serve integration with test

---

versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md

Made the following changes to flask+mongo python sample for Macos:
- Removed Keploy colima for macos.
- Removed Creating Docker Volume for macos
- Refactored keploy record command for macos.
- Refactored POST request 
- Added --rm to the application docker commands.
Fixes #1399 
NIL
NIL

[docs]: update missing information in the flask+mongo python sample

---

versioned_docs/version-2.0.0/keploy-cloud/time-freezing.md
versioned_sidebars/version-2.0.0-sidebars.json

docs: add timefreezing to keploy cloud

---

docusaurus.config.js
src/theme/DocItem/index.js
versioned_docs/version-1.0.0/concepts/what-is-a-keploy-sdk.md
versioned_docs/version-1.0.0/devtools/introduction.md
versioned_docs/version-1.0.0/go/quickstart/gin-mongo.md
versioned_docs/version-1.0.0/java/quickstart/quickstart.md
versioned_docs/version-2.0.0/concepts/index.md
versioned_docs/version-2.0.0/dependencies/index.md
versioned_docs/version-2.0.0/dependencies/mongo.md
versioned_docs/version-2.0.0/keploy-explained/docs-dev-guide.md
versioned_docs/version-2.0.0/operation/browser-extension.md
versioned_docs/version-2.0.0/operation/record.md
versioned_docs/version-2.0.0/operation/test.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/quickstart/samples-java.md
versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md
versioned_docs/version-2.0.0/server/sdk-installation/go-sdk.md
versioned_docs/version-2.0.0/server/windows/installation.md

Added the code blocks and code Highlighting

---

src/css/custom.css

Fixes the background color of codeBlocks in light mode.
...

setting the background of codeBlocks correctly

---

versioned_docs/version-2.0.0/server/sdk-installation/java-sdk.md

Updated Java unit integration file content
...

update: java unit integration

---

versioned_docs/version-2.0.0/server/sdk-installation/typescript-sdk.md

refactor:jest related docs

---

versioned_docs/version-2.0.0/server/sdk-installation/typescript-sdk.md

refactor:npm i sdk

---

versioned_docs/version-2.0.0/server/sdk-installation/python-sdk.md

docs: fix indent

---

CODE_OF_CONDUCT.md
README.md
src/components/Community.js
versioned_docs/version-2.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-2.0.0/server/sdk-installation/typescript-sdk.md

fix:sdk for ts

---

versioned_docs/version-2.0.0/server/sdk-installation/java-sdk.md

docs: add imports and class block for junit

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md
versioned_docs/version-2.0.0/server/sdk-installation/typescript-sdk.md

refactor: add docs for generateTestReport and removeUnusedMocks

---

versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md

Since the service is  set up to listen on port 8000 (refer to the compose file), we should make a request to `http://localhost:8000`
...

Fix: route request to correct port 8000

---

src/css/custom.css

Moved Installation Table into a react component and used `useColorMode` hook from `@docusaurus/theme-common`. To change the title colors with changes in the theme.
Fixes # [issue](https://github.com/keploy/keploy/issues/1756)
...

Fix: Table Titles not visible in dark mode

---

versioned_docs/version-2.0.0/server/sdk-installation/java-sdk.md

Bumped the version to 1.3.9
...

refactor: updating the version

---

versioned_docs/version-2.0.0/server/sdk-installation/python-sdk.md

Fixed the link navigations in PyTest Documentation
Fixes [#1844](https://github.com/keploy/keploy/issues/1844)
The build is successful

fix: pytest documentation

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md

Added normalization cmd related docs
...

docs: add normalize info

---

versioned_docs/version-2.0.0/concepts/installation.md
versioned_docs/version-2.0.0/keploy-cloud/installation.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo-local.md
versioned_docs/version-2.0.0/server/linux/installation.md
versioned_docs/version-2.0.0/server/macos/installation.md
versioned_docs/version-2.0.0/server/windows/installation.md

Change URL of keploy install script both in open source and enterprise section
...

fix: change keploy installation url

---

versioned_docs/version-2.0.0/running-keploy/configuration-file.md

Record filters and bypassRules have been documented with examples.

fix: Added documentation for record filters and bypass rules

---

versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/running-keploy/configuration-file.md
versioned_docs/version-2.0.0/server/sdk-installation/python-sdk.md

feat: update keploy config guide

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md
versioned_docs/version-2.0.0/server/sdk-installation/go-sdk.md

Replace --withCoverage to --goCoverage

fix: --withCoverage to --goCoverage

---

versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_sidebars/version-2.0.0-sidebars.json

Merged and fixed the documentation of flask + mongo app
The build is successful

Merged and fixed the documentation of flask + mongo app

---

versioned_docs/version-2.0.0/keploy-cloud/time-freezing.md
versioned_docs/version-2.0.0/quickstart/go-mux-sql.md
versioned_docs/version-2.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-2.0.0/quickstart/node-express-mongoose.md
versioned_docs/version-2.0.0/quickstart/node-jwt-sql.md
versioned_docs/version-2.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-2.0.0/quickstart/samples-echo.md
versioned_docs/version-2.0.0/quickstart/samples-go-gin-mongo.md
versioned_docs/version-2.0.0/running-keploy/cli-commands.md
versioned_docs/version-2.0.0/running-keploy/configuration-file.md
versioned_docs/version-2.0.0/running-keploy/docker-tls.md
versioned_docs/version-2.0.0/running-keploy/unit-test-generator.md

feat: updated docs with kebab case

---

versioned_docs/version-2.0.0/keploy-cloud/time-freezing.md

Add the Go time freezing docs
Fixes https://github.com/keploy/keploy/issues/2067

feat: go time freezing docs

---

versioned_docs/version-2.0.0/keploy-cloud/time-freezing.md

Go time freeze docs

---

versioned_docs/version-2.0.0/concepts/installation.md

Updated docs to use ```config --generate``` on Keploy installation page.
Docs - not tested
This was misleading for me:
...

Update docs to use config --generate

---

versioned_docs/version-2.0.0/concepts/what-are-keploy-features.md
versioned_docs/version-2.0.0/concepts/what-is-keploy.md

The GIF gets grainy and pixelated in the dark mode, the solution is to change the background colour of the image to white.
Fixes https://github.com/keploy/keploy/issues/2020

Solves GIFs seems grainy/pixelated in dark mode

---

src/theme/NavbarItem/DropdownNavbarItem.js

Fixed Redirection when we click on version 2.0.0 option in navbar.
Fixes [#issue2106](https://github.com/keploy/keploy/issues/2106)
...

fix: fixed redirection on versions

---

versioned_docs/version-2.0.0/keploy-cloud/deduplication.md

Updated the documentation according to the new dedup.
[Closes](https://github.com/keploy/enterprise/issues/322)
...

fix: updated the documentation according to the new dedup

---

versioned_docs/version-2.0.0/running-keploy/cli-commands.md

Fixes [#2056](https://github.com/keploy/keploy/issues/2056)
...

docs for new flag disable-line-coverage

---

versioned_docs/version-2.0.0/quickstart/go-fasthttp-postgres.md
versioned_sidebars/version-2.0.0-sidebars.json

fixes: [2166](https://github.com/keploy/keploy/issues/2166)
added documenation for fasthttp-postgress application in docs website.
cc @Sonichigo

docs: added fasthttp-postgress documentation

---

versioned_sidebars/version-2.0.0-sidebars.json

Added sidebars for sample apps

---

README.md

Slack URL in the Readme.md file, which was not working previously

Updated Slack URL in the README.md

---

versioned_docs/version-2.0.0/concepts/reference/glossary/integration-testing.md

Updated the content for integrating testing glossary term

docs: update integration-testing.md

---

versioned_docs/version-2.0.0/keploy-explained/mac-linux.md
versioned_docs/version-2.0.0/quickstart/samples-bunjs.md

Added bun installation, new docker-network, and mentioned error messages

---

src/pages/concepts/reference/glossary.js
versioned_docs/version-2.0.0/concepts/reference/glossary/grey-box-testing.md

Updated the "Gray Box Testing" page

Updated "Gray Box Testing" page

---

versioned_docs/version-2.0.0/server/windows/installation.md

Windows wsl command update 

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

chore: change the aws url for keploy java agent

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

chore: add note for windows

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

chore: update windows karaf env step

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

This pull request includes several changes to the `versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md` file. The changes focus on simplifying the instructions for recording and running tests with Keploy in Apache Karaf.
Simplification of instructions:
* Removed the section on updating `config.properties` to allow OSGi bundles to access Keploy artifacts.
* Simplified the steps for recording test cases by removing the need to restart Apache Karaf with the `KEPLOY_MODE` environment variable set to `RECORD`.
* Simplified the steps for running Keploy tests by removing the need to restart Apache Karaf with the `KEPLOY_MODE` environment variable set to `test`.
Please run npm run build and npm run serve to check if …

chore: update keploy-karaf.md

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

chore: update karaf docs

---

versioned_docs/version-2.0.0/running-keploy/keploy-karaf.md

chore: update docs

---

versioned_docs/version-2.0.0/running-keploy/configuration-file.md

chore: add instruction to make entire body global noise

---

versioned_docs/version-2.0.0/keploy-cloud/time-freezing.md
versioned_docs/version-2.0.0/running-keploy/docker-tls.md

chore: update timefreezing and tls docs

---

versioned_docs/version-2.0.0/concepts/reference/glossary/behaviour-driven-development.md
versioned_docs/version-2.0.0/concepts/reference/glossary/idempotency.md
versioned_docs/version-2.0.0/concepts/reference/glossary/test-driven-development.md

This pull request includes multiple changes to improve the glossary terms focusing on Idempotency, TDD and BDD
Locally checked via `npm run build`

feat: split idemotency and tdd/bdd

---

docusaurus.config.js
src/pages/privacy-policy.js

Fixed the security url that was redirecting to a blank/broken page
Yes

fix: security url fix

---

versioned_docs/version-2.0.0/quickstart/python-flask-mongo.md

Updated the Quickstart documentation for python and mongo
Yes

chore:update flask mongo quickstart

---

versioned_docs/version-2.0.0/quickstart/java-spring-boot-openhospital.md
versioned_sidebars/version-2.0.0-sidebars.json

I have added new java QuickStart sample.  (Not tested)

Added New quickstart Java Sample (Openhospital)

---

README.md

- Added a reference to **Docusaurus** under the **Technology Stack** section in the `README.md` file.
This PR is not linked to any existing issue.
- No code changes were made.
- Verified that the Markdown renders correctly in GitHub preview.

Added Docusaurus to the Technology Stack section in README

---

src/components/Intro.js

Under Dependencies support, the hover:underline was not present for lower three options. It was fixed by adding the tailwind feature in the relevant classNames
This PR Resolves #(539)
Styling change
Please run npm run build and npm run serve to check if the changes are working as expected.

Update Intro.js - fixed underline issue under Dependencies Support

---

versioned_docs/version-3.0.0/running-keploy/review-and-improve-ai-generated-tests.md
versioned_docs/version-3.0.0/running-keploy/run-ai-generated-api-tests.md
versioned_sidebars/version-3.0.0-sidebars.json

This pull request adds new documentation to enhance the usability and understanding of Keploy's AI-generated API testing features. The most important changes include the introduction of assertion types and examples, a guide for running AI-generated API tests, and updates to the sidebar configuration to include the new documentation.
* **Assertion Types and Examples**: Added a detailed section outlining nine assertion primitives supported by Keploy, complete with examples and YAML snippets. This helps users understand how to refine test assertions effectively. (`versioned_docs/version-3.0.0/running-keploy/review-and-improve-ai-generated-tests.md`, [versioned_docs/version-3.0.0/running-keploy/review-and-improve-ai-generated-tests.mdR56-R76](diffhunk://#diff-eba29bbd71a0c7324528f869d05827a524 …

Added run, edited existing with changes

---

src/pages/security.js
versioned_docs/version-1.0.0/concepts/reference/glossary/stubs.md
versioned_docs/version-1.0.0/java/replay.md
versioned_docs/version-1.0.0/operation/browser-extension.md
versioned_docs/version-2.0.0/concepts/reference/glossary/black-box-testing.md
versioned_docs/version-2.0.0/concepts/reference/glossary/idempotency.md
versioned_docs/version-2.0.0/concepts/reference/glossary/manual-testing.md
versioned_docs/version-2.0.0/concepts/reference/glossary/microservice-testing.md
versioned_docs/version-2.0.0/concepts/reference/glossary/stubs.md
versioned_docs/version-2.0.0/concepts/reference/glossary/test-driven-development.md
versioned_docs/version-2.0.0/concepts/reference/glossary/white-box-testing.md
versioned_docs/version-2.0.0/keploy-cloud/new-application.md
versioned_docs/version-2.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-2.0.0/quickstart/sanic-mongo.md
versioned_docs/version-2.0.0/server/sdk-installation/index.md
versioned_docs/version-3.0.0/concepts/reference/glossary/black-box-testing.md
versioned_docs/version-3.0.0/concepts/reference/glossary/idempotency.md
versioned_docs/version-3.0.0/concepts/reference/glossary/manual-testing.md
versioned_docs/version-3.0.0/concepts/reference/glossary/microservice-testing.md
versioned_docs/version-3.0.0/concepts/reference/glossary/stubs.md
versioned_docs/version-3.0.0/concepts/reference/glossary/test-driven-development.md
versioned_docs/version-3.0.0/concepts/reference/glossary/white-box-testing.md
versioned_docs/version-3.0.0/keploy-cloud/new-application.md
versioned_docs/version-3.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-3.0.0/quickstart/sanic-mongo.md
versioned_docs/version-3.0.0/server/sdk-installation/index.md

This PR focuses on improving the Click-Through Rate (CTR) by optimizing key elements of the user experience. The changes aim to increase engagement and make the content more appealing to users.

Added ctr improvement

---

src/css/custom.css

I have fixed the pagination issue 
This PR Resolves #(2810)

fix: pagination issue

---

versioned_docs/version-3.0.0/keploy-explained/api-testing-faq.md
versioned_docs/version-3.0.0/keploy-explained/unit-testing-faq.md
versioned_sidebars/version-3.0.0-sidebars.json

I have fixed the FAQs pages alignment issues for all three products.

fix: faqs page alignment issues

---

src/theme/NotFound/Content/index.js
src/theme/NotFound/index.js
versioned_sidebars/version-3.0.0-sidebars.json

I have fixed the redirecting all non-resolving pages to home page

fix: redirect non resolving page

---

versioned_docs/version-3.0.0/running-keploy/configuration-file.md

This pull request updates the documentation for the `record` section in the Keploy configuration file, enhancing the explanation of the `filters` parameter by introducing the `matchType` option and providing a clearer example.
* **`filters` parameter enhancement**: Added the `matchType` option to control how `urlMethods` and `headers` are evaluated, with support for `"AND"` and `"OR"` conditions.
* **Updated example**: Modified the example under `filters` to include `matchType: "AND"` and updated the headers and description to reflect the new behavior.
Please run npm run build and npm run serve to check if the changes are working as expected. Please include screenshots of the output of both the commands. Add …

feat: update filter doc

---

versioned_docs/version-3.0.0/running-keploy/configuration-file.md

Added a new way to manage secrets using a secrets.yml file 

feat: add secret management

---

versioned_docs/version-3.0.0/running-keploy/configuration-file.md

fix: pipeline

---

versioned_docs/version-3.0.0/quickstart/go-gin-redis.md

[Fix]: update the postgres ref in gin-redis guide

---

package.json
src/components/Community.js
src/components/QuickStartGuide.js
src/components/StartKeploy.js
src/components/StartKeployDocker.js
src/components/index.js
src/pages/index.js
versioned_docs/version-3.0.0/quickstart/code-coverage.md
versioned_docs/version-3.0.0/quickstart/csharp-dotnet-postgres.md
versioned_docs/version-3.0.0/quickstart/flask-redis.md
versioned_docs/version-3.0.0/quickstart/java-spring-boot-mongo.md
versioned_docs/version-3.0.0/quickstart/java-spring-boot-xml.md
versioned_docs/version-3.0.0/quickstart/java-spring-postgres.md
versioned_docs/version-3.0.0/quickstart/python-django-sql.md
versioned_docs/version-3.0.0/quickstart/python-fastapi-sql.md
versioned_docs/version-3.0.0/quickstart/python-fastapi-twilio.md
versioned_docs/version-3.0.0/quickstart/python-flask-mongo.md
versioned_docs/version-3.0.0/quickstart/sample-rust-crud-mongo.md
versioned_docs/version-3.0.0/quickstart/samples-java.md
versioned_docs/version-3.0.0/quickstart/samples-rust.md
versioned_docs/version-3.0.0/quickstart/sanic-mongo.md
versioned_docs/version-3.0.0/running-keploy/api-testing-chrome-extension.md
versioned_docs/version-3.0.0/running-keploy/api-testing-tool-ai-powered.md
versioned_docs/version-3.0.0/server/installation_tabs.md
versioned_sidebars/version-3.0.0-sidebars.json

Revamp the home page and the quickstart guide

feat: revamp home page and quickstart guide

---

.github/workflows/build_and_check.yml
versioned_docs/version-2.0.0/keploy-explained/debugger-guide.md
versioned_docs/version-3.0.0/keploy-explained/debugger-guide.md

I have updated the Node.js version in the CI build pipeline to fix the build failing issue.

 fix: updated the build ci pipeline
